Category.destroy_all
Goal.destroy_all
User.destroy_all
GoalsUser.destroy_all
Connection.destroy_all


Category.create(name:"Movies")
Category.create(name:"TV Shows")
Category.create(name:"Books")
Category.create(name:"Travel")
Category.create(name:"Restaurants")


Goal.create(task:"Harry Potter and the Goblet of Fire", category_id:1, api_id: "tt0330373")
Goal.create(task:"Pacific Rim", category_id:1, api_id: "tt1663662")
Goal.create(task:"Muppets", category_id:1, api_id: "tt1204342")
Goal.create(task:"Spectre", category_id:1, api_id: "tt2379713")
Goal.create(task:"The Man with the Golden Gun", category_id:1, api_id: "tt0071807")
Goal.create(task:"The Notebook", category_id:1, api_id: "tt0332280")
Goal.create(task:"Transformers", category_id:1, api_id: "tt0418279")
Goal.create(task:"The Devil Wears Prada", category_id:1, api_id: "tt0458352")
Goal.create(task:"The Godfather", category_id:1, api_id: "tt0068646")
Goal.create(task:"Scarface", category_id:1, api_id: "tt0086250")
Goal.create(task:"Horton Hears a Who", category_id:1, api_id: "tt0451079")
Goal.create(task:"Pokemon 2000", category_id:1, api_id: "tt0382918")

Goal.create(task:"Game of Thrones", category_id:2, image_url: "http://media.moddb.com/images/members/1/123/122021/profile/c9lzmv4d3mgzpnyntz7s.jpg", data: {:actors=>"Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington", :plot=>"Nine noble families fight for control over the mythical lands of Westeros; A forgotten race returns after being dormant for thousands of years.", :year=>"2011–"})
Goal.create(task:"The Americans", category_id:2, api_id: "tt2149175")
Goal.create(task:"Chopped", category_id:2, api_id: "tt1353281")
Goal.create(task:"Iron Chef", category_id:2, api_id: "tt0220265")
Goal.create(task:"Smallville", category_id:2, api_id: "tt0279600")
Goal.create(task:"Whale Wars", category_id:2, api_id: "tt1195419")
Goal.create(task:"Survivorman", category_id:2, api_id: "tt0770659")
Goal.create(task:"Sons of Anarchy", category_id:2, api_id: "tt1124373")
Goal.create(task:"Duck Dynasty", category_id:2, api_id: "tt2229907")
Goal.create(task:"Legion", category_id:2, api_id: "tt1038686")
Goal.create(task:"Westworld", category_id:2, api_id: "tt0475784")
Goal.create(task:"Silicon Valley", category_id:2, api_id: "tt2575988")
Goal.create(task:"Parks and Recreation", category_id:2, api_id: "tt1266020")
Goal.create(task:"The Office", category_id:2, api_id: "tt0386676")

Goal.create(task:"Dr. No: James Bond 007", category_id:3, api_id: "83I9F0ChS1oC")
Goal.create(task:"Goldeneye 007: Unauthorized Game Secrets", category_id:3, api_id: "KzmZPQAACAAJ")
Goal.create(task:"A Tale of Two Cities", category_id:3, api_id: "nuTsYEwx_iwC")
Goal.create(task:"The Hobbit", category_id:3, api_id: "hFfhrCWiLSMC")
Goal.create(task:"Moonraker", category_id:3, api_id: "Zph_XxHy4AAC")
Goal.create(task:"Jurassic Park", category_id:3, api_id: "I79dV_HQvykC")
Goal.create(task:"The Lost World", category_id:3, api_id: "oNEQAAAAYAAJ")
Goal.create(task:"The DaVinci Code", category_id:3, api_id: "YuDl2Wl651AC")
Goal.create(task:"The Kite Runner", category_id:3, api_id: "MH48bnzN0LUC")
Goal.create(task:"Romeo and Juliet", category_id:3, api_id: "6rhaAAAAcAAJ")
Goal.create(task:"Much Ado About Nothing", category_id:3, api_id: "0GmmbXRahAkC")
Goal.create(task:"Twenty Thousand Leagues Under the Sea", category_id:3, api_id: "RqlEAAAAYAAJ")
Goal.create(task:"Friday Night Lights", category_id:3, api_id: "aRZpCQAAQBAJ")
Goal.create(task:"The Blindside", category_id:3, api_id: "jeVS4jRjSlQC")

Goal.create(task:"Paris", category_id:4, api_id: "ChIJD7fiBh9u5kcRYJSMaMOCCwQ")
Goal.create(task:"Milan", category_id:4, api_id: "ChIJ53USP0nBhkcRjQ50xhPN_zw")
Goal.create(task:"Rome", category_id:4, api_id: "ChIJDYryPb4O2YkR97P8bHEaoEo")
Goal.create(task:"Toronto", category_id:4, api_id: "ChIJpTvG15DL1IkRd8S0KlBVNTI")
Goal.create(task:"Seoul", category_id:4, api_id: "ChIJzWXFYYuifDUR64Pq5LTtioU")
Goal.create(task:"Beijing", category_id:4, api_id: "ChIJuSwU55ZS8DURiqkPryBWYrk")
Goal.create(task:"Tokyo", category_id:4, api_id: "ChIJ51cu8IcbXWARiRtXIothAS4")
Goal.create(task:"Tanzania", category_id:4, api_id: "ChIJEaFpSDFRSxgRMMTBSzEXWog")
Goal.create(task:"New Zealand", category_id:4, api_id: "ChIJh5Z3Fw4gLG0RM0dqdeIY1rE")
Goal.create(task:"Christmas Island", category_id:4, api_id: "ChIJz6fA4yea9S4RFup1BAnW5xU")
Goal.create(task:"Iceland", category_id:4, api_id: "ChIJQ2Dro1Ir0kgRmkXB5TQEim8")
Goal.create(task:"New York City", category_id:4, api_id: "ChIJOwg_06VPwokRYv534QaPC8g")
Goal.create(task:"Madrid", category_id:4, api_id: "ChIJgTwKgJcpQg0RaSKMYcHeNsQ")
Goal.create(task:"Moscow", category_id:4, api_id: "ChIJDaDKkrXCxIkR16VXi1WamHU")

Goal.create(task:"Le Bernardin", category_id:5, api_id: "ChIJVSKXkPhYwokRVgXdrRfFxh0")
Goal.create(task:"McDonald's", category_id:5, api_id: "ChIJ2_VLfRdawokRXKfA6CMf5YQ")
Goal.create(task:"Per Se", category_id:5, api_id: "ChIJp3PsL_ZYwokRZYqs_40RJF4")
Goal.create(task:"Eleven Madison Park", category_id:5, api_id: "ChIJEWbXz6ZZwokRLKmKrtPfVFY")
Goal.create(task:"Jean-Georges", category_id:5, api_id: "ChIJh5JzbfZYwokRR7KqJOksL7Y")
Goal.create(task:"The Seafire Grill", category_id:5, api_id: "ChIJpYNIR_1YwokRNMXI4Qk1lwQ")
Goal.create(task:"Gotham Bar and Grill", category_id:5, api_id: "ChIJZ72FzplZwokRmcA7CQzDMj0")
Goal.create(task:"Somtum Der", category_id:5, api_id: "ChIJY_1BtoJZwokR-sB-pdEPW44")
Goal.create(task:"Morimoto", category_id:5, api_id: "ChIJTyXzusBZwokRtkOSoqQgYAM")
Goal.create(task:"Momofuku Ssam Bar", category_id:5, api_id: "ChIJkXQ3_INZwokRbCMEByaQ_VE")
Goal.create(task:"Alinea", category_id:5, api_id: "ChIJuyI60yLTD4gROwTWENq1He0")
Goal.create(task:"Peter Luger Steakhouse", category_id:5, api_id: "ChIJR_bK295bwokR8gM6QgEdmkY")
Goal.create(task:"Smith and Wollensky", category_id:5, api_id: "ChIJSRfEz-JYwokRA5qI_DOzkKg")

User.create(first_name:"Matt", last_name:"Kim", username:"MKto", email:"matt@email.com", password:"password")
User.create(first_name:"Nanu", last_name:"Brar", username:"Meow", email:"nanu@email.com", password:"password")
User.create(first_name:"Kevin", last_name:"Brody", username:"Kdawgg", email:"kevin@email.com", password:"password")
User.create(first_name:"James", last_name:"Richards", username:"Jdawgg", email:"james@email.com", password:"password")
User.create(first_name:"Shane", last_name:"Murphy", username:"shane", email:"shane@email.com", password:"password")
User.create(first_name:"Bryan", last_name:"Mateer", username:"bryan", email:"bryan@email.com", password:"password")
User.create(first_name:"Adriel", last_name:"Sapporta", username:"adriel", email:"adriel@email.com", password:"password")
User.create(first_name:"Carl", last_name:"Williams", username:"carl", email:"carl@email.com", password:"password")
User.create(first_name:"Billy", last_name:"Billiamson", username:"billy", email:"billy@email.com", password:"password")
User.create(first_name:"Cindy", last_name:"Liebenson", username:"cindy", email:"cindy@email.com", password:"password")
User.create(first_name:"Meghan", last_name:"O'Callahan", username:"meghan", email:"meghan@email.com", password:"password")

GoalsUser.create(user_id: 1, goal_id: 1)
GoalsUser.create(user_id: 1, goal_id: 6)
GoalsUser.create(user_id: 1, goal_id: 46)
GoalsUser.create(user_id: 1, goal_id: 80)
GoalsUser.create(user_id: 1, goal_id: 76)
GoalsUser.create(user_id: 1, goal_id: 34)
GoalsUser.create(user_id: 1, goal_id: 63)
GoalsUser.create(user_id: 1, goal_id: 12)
GoalsUser.create(user_id: 1, goal_id: 7)
GoalsUser.create(user_id: 1, goal_id: 54)
GoalsUser.create(user_id: 1, goal_id: 23)
GoalsUser.create(user_id: 1, goal_id: 3)
GoalsUser.create(user_id: 1, goal_id: 9)
GoalsUser.create(user_id: 1, goal_id: 79)

GoalsUser.create(user_id: 2, goal_id: 1)
GoalsUser.create(user_id: 2, goal_id: 6)
GoalsUser.create(user_id: 2, goal_id: 46)
GoalsUser.create(user_id: 2, goal_id: 80)
GoalsUser.create(user_id: 2, goal_id: 76)
GoalsUser.create(user_id: 2, goal_id: 34)
GoalsUser.create(user_id: 2, goal_id: 65)
GoalsUser.create(user_id: 2, goal_id: 15)
GoalsUser.create(user_id: 2, goal_id: 8)
GoalsUser.create(user_id: 2, goal_id: 64)
GoalsUser.create(user_id: 2, goal_id: 22)
GoalsUser.create(user_id: 2, goal_id: 13)
GoalsUser.create(user_id: 2, goal_id: 88)
GoalsUser.create(user_id: 2, goal_id: 81)

GoalsUser.create(user_id: 3, goal_id: 82)
GoalsUser.create(user_id: 3, goal_id: 5)
GoalsUser.create(user_id: 3, goal_id: 45)
GoalsUser.create(user_id: 3, goal_id: 79)
GoalsUser.create(user_id: 3, goal_id: 75)
GoalsUser.create(user_id: 3, goal_id: 33)
GoalsUser.create(user_id: 3, goal_id: 62)
GoalsUser.create(user_id: 3, goal_id: 11)
GoalsUser.create(user_id: 3, goal_id: 6)
GoalsUser.create(user_id: 3, goal_id: 53)
GoalsUser.create(user_id: 3, goal_id: 22)
GoalsUser.create(user_id: 3, goal_id: 2)
GoalsUser.create(user_id: 3, goal_id: 8)
GoalsUser.create(user_id: 3, goal_id: 78)

GoalsUser.create(user_id: 4, goal_id: 3)
GoalsUser.create(user_id: 4, goal_id: 8)
GoalsUser.create(user_id: 4, goal_id: 48)
GoalsUser.create(user_id: 4, goal_id: 82)
GoalsUser.create(user_id: 4, goal_id: 78)
GoalsUser.create(user_id: 4, goal_id: 36)
GoalsUser.create(user_id: 4, goal_id: 65)
GoalsUser.create(user_id: 4, goal_id: 14)
GoalsUser.create(user_id: 4, goal_id: 9)
GoalsUser.create(user_id: 4, goal_id: 56)
GoalsUser.create(user_id: 4, goal_id: 25)
GoalsUser.create(user_id: 4, goal_id: 5)
GoalsUser.create(user_id: 4, goal_id: 11)
GoalsUser.create(user_id: 4, goal_id: 81)

GoalsUser.create(user_id: 5, goal_id: 4)
GoalsUser.create(user_id: 5, goal_id: 9)
GoalsUser.create(user_id: 5, goal_id: 49)
GoalsUser.create(user_id: 5, goal_id: 83)
GoalsUser.create(user_id: 5, goal_id: 79)
GoalsUser.create(user_id: 5, goal_id: 37)
GoalsUser.create(user_id: 5, goal_id: 66)
GoalsUser.create(user_id: 5, goal_id: 15)
GoalsUser.create(user_id: 5, goal_id: 10)
GoalsUser.create(user_id: 5, goal_id: 57)
GoalsUser.create(user_id: 5, goal_id: 26)
GoalsUser.create(user_id: 5, goal_id: 6)
GoalsUser.create(user_id: 5, goal_id: 12)
GoalsUser.create(user_id: 5, goal_id: 82)

GoalsUser.create(user_id: 6, goal_id: 5)
GoalsUser.create(user_id: 6, goal_id: 10)
GoalsUser.create(user_id: 6, goal_id: 50)
GoalsUser.create(user_id: 6, goal_id: 84)
GoalsUser.create(user_id: 6, goal_id: 80)
GoalsUser.create(user_id: 6, goal_id: 38)
GoalsUser.create(user_id: 6, goal_id: 67)
GoalsUser.create(user_id: 6, goal_id: 16)
GoalsUser.create(user_id: 6, goal_id: 11)
GoalsUser.create(user_id: 6, goal_id: 48)
GoalsUser.create(user_id: 6, goal_id: 27)
GoalsUser.create(user_id: 6, goal_id: 7)
GoalsUser.create(user_id: 6, goal_id: 13)
GoalsUser.create(user_id: 6, goal_id: 83)

GoalsUser.create(user_id: 7, goal_id: 6)
GoalsUser.create(user_id: 7, goal_id: 11)
GoalsUser.create(user_id: 7, goal_id: 51)
GoalsUser.create(user_id: 7, goal_id: 85)
GoalsUser.create(user_id: 7, goal_id: 81)
GoalsUser.create(user_id: 7, goal_id: 39)
GoalsUser.create(user_id: 7, goal_id: 68)
GoalsUser.create(user_id: 7, goal_id: 17)
GoalsUser.create(user_id: 7, goal_id: 12)
GoalsUser.create(user_id: 7, goal_id: 59)
GoalsUser.create(user_id: 7, goal_id: 28)
GoalsUser.create(user_id: 7, goal_id: 8)
GoalsUser.create(user_id: 7, goal_id: 14)
GoalsUser.create(user_id: 7, goal_id: 84)

GoalsUser.create(user_id: 8, goal_id: 7)
GoalsUser.create(user_id: 8, goal_id: 12)
GoalsUser.create(user_id: 8, goal_id: 52)
GoalsUser.create(user_id: 8, goal_id: 86)
GoalsUser.create(user_id: 8, goal_id: 82)
GoalsUser.create(user_id: 8, goal_id: 40)
GoalsUser.create(user_id: 8, goal_id: 69)
GoalsUser.create(user_id: 8, goal_id: 19)
GoalsUser.create(user_id: 8, goal_id: 13)
GoalsUser.create(user_id: 8, goal_id: 55)
GoalsUser.create(user_id: 8, goal_id: 22)
GoalsUser.create(user_id: 8, goal_id: 2)
GoalsUser.create(user_id: 8, goal_id: 18)
GoalsUser.create(user_id: 8, goal_id: 33)

GoalsUser.create(user_id: 9, goal_id: 32)
GoalsUser.create(user_id: 9, goal_id: 14)
GoalsUser.create(user_id: 9, goal_id: 48)
GoalsUser.create(user_id: 9, goal_id: 80)
GoalsUser.create(user_id: 9, goal_id: 76)
GoalsUser.create(user_id: 9, goal_id: 34)
GoalsUser.create(user_id: 9, goal_id: 63)
GoalsUser.create(user_id: 9, goal_id: 13)
GoalsUser.create(user_id: 9, goal_id: 3)
GoalsUser.create(user_id: 9, goal_id: 4)
GoalsUser.create(user_id: 9, goal_id: 39)
GoalsUser.create(user_id: 9, goal_id: 54)
GoalsUser.create(user_id: 9, goal_id: 56)
GoalsUser.create(user_id: 9, goal_id: 79)

GoalsUser.create(user_id: 10, goal_id: 8)
GoalsUser.create(user_id: 10, goal_id: 6)
GoalsUser.create(user_id: 10, goal_id: 73)
GoalsUser.create(user_id: 10, goal_id: 22)
GoalsUser.create(user_id: 10, goal_id: 76)
GoalsUser.create(user_id: 10, goal_id: 34)
GoalsUser.create(user_id: 10, goal_id: 63)
GoalsUser.create(user_id: 10, goal_id: 12)
GoalsUser.create(user_id: 10, goal_id: 7)
GoalsUser.create(user_id: 10, goal_id: 54)
GoalsUser.create(user_id: 10, goal_id: 23)
GoalsUser.create(user_id: 10, goal_id: 16)
GoalsUser.create(user_id: 10, goal_id: 9)
GoalsUser.create(user_id: 10, goal_id: 83)

Connection.create(friender_id: 1, friendee_id: 2)
Connection.create(friender_id: 1, friendee_id: 3)
Connection.create(friender_id: 2, friendee_id: 3)
Connection.create(friender_id: 2, friendee_id: 4)
Connection.create(friender_id: 3, friendee_id: 4)
Connection.create(friender_id: 3, friendee_id: 5)
Connection.create(friender_id: 4, friendee_id: 5)
Connection.create(friender_id: 4, friendee_id: 6)
Connection.create(friender_id: 5, friendee_id: 6)
Connection.create(friender_id: 5, friendee_id: 7)
Connection.create(friender_id: 6, friendee_id: 7)
Connection.create(friender_id: 6, friendee_id: 8)
Connection.create(friender_id: 7, friendee_id: 8)
Connection.create(friender_id: 7, friendee_id: 9)
Connection.create(friender_id: 8, friendee_id: 9)
Connection.create(friender_id: 8, friendee_id: 10)
Connection.create(friender_id: 9, friendee_id: 10)
Connection.create(friender_id: 9, friendee_id: 1)
Connection.create(friender_id: 10, friendee_id: 1)
Connection.create(friender_id: 10, friendee_id: 2)
